// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-IMe1lUQ807L3ivSQSVNm2O4SQtVmNhE',
    appId: '1:472131951424:web:a95c9b7c9fdf0db59c38a5',
    messagingSenderId: '472131951424',
    projectId: 'recipeapp-dc3a8',
    authDomain: 'recipeapp-dc3a8.firebaseapp.com',
    storageBucket: 'recipeapp-dc3a8.appspot.com',
    measurementId: 'G-Q979GY2FWE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxw4haFYiOxdTHpHx8lcUAYH-UQsssjdg',
    appId: '1:472131951424:android:29318b603e27f74b9c38a5',
    messagingSenderId: '472131951424',
    projectId: 'recipeapp-dc3a8',
    storageBucket: 'recipeapp-dc3a8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxqm_vgtg0nFN_WtrX-88sGqynMUJJW4I',
    appId: '1:472131951424:ios:e7a96cba0ea1bb179c38a5',
    messagingSenderId: '472131951424',
    projectId: 'recipeapp-dc3a8',
    storageBucket: 'recipeapp-dc3a8.appspot.com',
    iosClientId: '472131951424-20c1gdngtmp430ku23mrsij2co776e26.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodrecipe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxqm_vgtg0nFN_WtrX-88sGqynMUJJW4I',
    appId: '1:472131951424:ios:e7a96cba0ea1bb179c38a5',
    messagingSenderId: '472131951424',
    projectId: 'recipeapp-dc3a8',
    storageBucket: 'recipeapp-dc3a8.appspot.com',
    iosClientId: '472131951424-20c1gdngtmp430ku23mrsij2co776e26.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodrecipe',
  );
}
